#!/usr/bin/env python3
"""Stage 00 — keygen (LOCAL, project owner). KIT-OWNED SHIM — do not edit.

Maps the argparse CLI onto ``local_project_owner.keygen`` and writes the two
fixed context filenames the platform expects. The crypto logic lives in
local_project_owner.py; this wrapper is identical across every application and is
regenerated by the kit (it is part of the trusted computing base, not the
application).

    python 00_keygen.py --out-dir DIR [--security {128,192,256}]
                        [--poly-modulus-degree N] [--plain-modulus T]
"""
from __future__ import annotations

import argparse
import pathlib

from local_project_owner import keygen

# This is a serialized context filename, not a credential literal.
SECRET_CONTEXT_FILENAME = "secret_context.tenseal"  # nosec B105
PUBLIC_CONTEXT_FILENAME = "public_context.tenseal"  # PUBLIC — the only half published


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Stage 00 — keygen (local).")
    parser.add_argument("--out-dir", required=True, type=pathlib.Path)
    parser.add_argument("--security", type=int, default=None)
    parser.add_argument("--poly-modulus-degree", type=int, default=None)
    parser.add_argument("--plain-modulus", type=int, default=None)
    args = parser.parse_args(argv)

    # Forward only the params the caller actually set; keygen owns the defaults.
    params = {
        "security": args.security,
        "poly_modulus_degree": args.poly_modulus_degree,
        "plain_modulus": args.plain_modulus,
    }
    secret_bytes, public_bytes = keygen(**{k: v for k, v in params.items() if v is not None})

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / SECRET_CONTEXT_FILENAME).write_bytes(secret_bytes)
    (args.out_dir / PUBLIC_CONTEXT_FILENAME).write_bytes(public_bytes)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
